"""sonic_disk_image: assemble a raw SONiC disk image and gzip-compress it.

Produces a root-free, mount-free GPT disk image consisting of three
partitions, then pigz-compresses the raw bytes to
sonic-<machine>.img.gz:

    +-------------------+  LBA   0       MBR boot sector: bytes [0..446)
    |  GRUB boot.img    |                = //grub:boot.img
    |  + GPT pMBR table |                  written by
    |                   |                  grub-bios-setup (which also
    |                   |                  patches kernel_sector LBA at
    |                   |                  offset 0x5c). Bytes [446..512)
    |                   |                  = sgdisk's GPT protective MBR.
    +-------------------+  LBA 2048      Partition 1: BIOS-BOOT (EF02,
    |  GRUB core.img    |  +1M           1 MiB). core.img generated by
    |  in BIOS Boot     |                host grub-mkimage and embedded
    |  Partition        |                by grub-bios-setup with prefix
    |                   |                = (hd0,gpt2)/onie/grub.
    +-------------------+  +onie_part_size_mb MiB
    |   ONIE-BOOT       |                Partition 2: ext4 (8300),
    |   ext4 partition  |  default       label "ONIE-BOOT". Built in
    |                   |  128 MiB       place via `mke2fs -E offset=<>
    |                   |                -d <onie_staging>` so no loop
    |                   |                mount or root is needed.
    +-------------------+
    |    SONiC-OS       |  remainder     Partition 3: ext4 (8300),
    |    ext4 partition |  of disk       label "SONiC-OS". Same in-place
    |                   |  (minus 1 MiB  mke2fs -d trick.
    |                   |   GPT backup)
    +-------------------+

Implementation notes:
  * No loop mounts, no root. mke2fs -E offset= writes the filesystem
    directly inside the raw disk file at a given byte offset; -d
    populates the FS from a staging directory at filesystem-creation
    time.
  * sgdisk writes the GPT in-place on the raw file (gptfdisk treats the
    file as a block device for I/O purposes).
  * GRUB stage installation uses hermetic grub-mkimage + grub-bios-setup
    (source-built cc_binary from GRUB 2.06 upstream). boot.img is
    checked into //grub/generated/ (512B, GRUB 2.06 vanilla). The *.mod
    files that grub-mkimage embeds into core.img come from the ONIE
    recovery ISO (extracted by onie_iso_extract into the ONIE-BOOT
    staging tar at onie/grub/i386-pc/), matching the GRUB version that
    a real ONIE installation would use.
  * grub-bios-setup runs fully sandboxed: the source-built tool is
    patched (//grub:grub-bios-setup-no-mountinfo.patch) so that when the
    staging directory has no real backing block device (overlayfs /
    tmpfs in the Bazel sandbox), it no longer aborts probing
    /proc/self/mountinfo -- it falls back to the destination disk image
    as the root device. Writing the MBR boot.img + embedding core.img
    into the BIOS Boot Partition of a raw image file never needed the
    host root device, so no `no-sandbox`/`local` or `overlay` symlink
    workaround is required.
  * Output is sized in MiB end-to-end (sgdisk LBA = MiB * 2048 for the
    default 512B sector).
"""

load("@tar.bzl//tar:tar.bzl", tar_lib = "tar_lib")

# Sub-MiB slack reserved at the disk tail for the GPT backup header (which
# sgdisk places in the last 33 sectors). 1 MiB is generous and keeps every
# partition aligned to a MiB boundary.
_GPT_BACKUP_RESERVE_MB = 1

def _sonic_disk_image_impl(ctx):
    out = ctx.actions.declare_file(ctx.attr.out)
    bsdtar = ctx.toolchains[tar_lib.toolchain_type]

    onie_staging = ctx.file.onie_boot_staging
    mke2fs = ctx.executable.mke2fs
    sgdisk = ctx.executable.sgdisk
    pigz = ctx.executable.pigz
    grub_mkimage = ctx.executable.grub_mkimage
    grub_bios_setup = ctx.executable.grub_bios_setup
    debugfs = ctx.executable.debugfs
    tar_reprefix = ctx.executable._tar_reprefix
    platform_imgs = ctx.files.grub_platform_imgs

    # SONiC-OS staging inputs (assembled into a tmpdir inside this one action,
    # so the staging tree never becomes an intermediate Bazel artifact).
    squashfs = ctx.file.squashfs
    boot_files = ctx.files.boot_files[0]
    initrd = ctx.file.initrd
    platform_tar = ctx.file.platform_tar
    dockerfs = ctx.file.dockerfs
    dockerfs_path = dockerfs.path if dockerfs else ""

    disk_mb = ctx.attr.disk_size_mb
    bios_mb = ctx.attr.bios_part_size_mb
    onie_mb = ctx.attr.onie_part_size_mb

    # Layout (MiB-aligned):
    #   [0 .. 1)             reserved (MBR + GPT primary header + table)
    #   [1 .. 1+bios)        BIOS-BOOT partition (sgdisk -n 1:2048:+bios_mb*M)
    #   [1+bios .. ...)      ONIE-BOOT partition (sgdisk -n 2:0:+onie_mb*M)
    #   [...   .. disk-1)    SONiC-OS  partition (sgdisk -n 3:0:0)
    #   [disk-1 .. disk)     reserved for GPT backup header + table
    onie_offset_mb = 1 + bios_mb
    sonic_offset_mb = onie_offset_mb + onie_mb
    sonic_size_mb = disk_mb - sonic_offset_mb - _GPT_BACKUP_RESERVE_MB

    if sonic_size_mb <= 0:
        fail(("sonic_disk_image %s: disk_size_mb=%d is too small for the " +
              "requested partitions (BIOS=%d MiB + ONIE=%d MiB + 2 MiB " +
              "for GPT headers); need disk_size_mb > %d.") % (
            ctx.label,
            disk_mb,
            bios_mb,
            onie_mb,
            sonic_offset_mb + _GPT_BACKUP_RESERVE_MB,
        ))

    inputs = [
        squashfs,
        boot_files,
        initrd,
        platform_tar,
        onie_staging,
        ctx.file.grub_boot_img,
    ] + platform_imgs
    if dockerfs:
        inputs.append(dockerfs)

    ctx.actions.run(
        executable = ctx.executable._assemble_sh,
        arguments = [
            squashfs.path,
            boot_files.path,
            platform_tar.path,
            dockerfs_path,
            ctx.attr.image_version,
            ctx.attr.machine,
            ctx.attr.platform,
            onie_staging.path,
            out.path,
            str(disk_mb),
            str(bios_mb),
            str(onie_offset_mb),
            str(onie_mb),
            str(sonic_offset_mb),
            str(sonic_size_mb),
            bsdtar.tarinfo.binary.path,
            mke2fs.path,
            sgdisk.path,
            pigz.path,
            ctx.file.grub_boot_img.path,
            grub_mkimage.path,
            grub_bios_setup.path,
            ctx.attr.grub_prefix,
            debugfs.path,
            initrd.path,
            tar_reprefix.path,
        ] + [f.path for f in platform_imgs],
        inputs = inputs,
        outputs = [out],
        tools = depset(
            direct = [mke2fs, sgdisk, pigz, grub_mkimage, grub_bios_setup, debugfs, tar_reprefix],
            transitive = [
                bsdtar.default.files,
                # py_binary output is a wrapper script; its runfiles carry the
                # interpreter + tar_reprefix.py, so they must travel with it.
                ctx.attr._tar_reprefix[DefaultInfo].default_runfiles.files,
            ],
        ),
        mnemonic = "SonicDiskImage",
        progress_message = "Assembling SONiC disk image %s" % out.short_path,
    )
    return [DefaultInfo(files = depset([out]))]

sonic_disk_image = rule(
    implementation = _sonic_disk_image_impl,
    doc = "Assemble a raw GPT disk image (BIOS-BOOT + ONIE-BOOT + SONiC-OS) in " +
          "one action: a small staging tree (image-<ver>/{boot,platform} + " +
          "machine.conf) is built in a tmpdir, the dockerfs store is streamed " +
          "re-rooted under image-<ver>/docker and merged with it into the " +
          "mke2fs -d - stdin tar (no on-disk extract), fs.squashfs is written " +
          "in by debugfs, then " +
          "the BIOS GRUB stage (boot.img + core.img) is installed via hermetic " +
          "grub-mkimage + grub-bios-setup (source-built from GRUB 2.06), and " +
          "the result is pigz-compressed to <out>. Mount-free / root-free.",
    attrs = {
        "squashfs": attr.label(
            mandatory = True,
            allow_single_file = True,
            doc = "SONiC fs.squashfs image. Copied verbatim to " +
                  "image-<version>/fs.squashfs in the staging tree.",
        ),
        "boot_files": attr.label(
            mandatory = True,
            doc = "A boot/-rooted tree artifact (kernel vmlinuz/config/" +
                  "System.map). Copied verbatim into image-<version>/, landing " +
                  "at image-<version>/boot/... Replaces the old boot_tar -- no " +
                  "pack/unpack.",
        ),
        "initrd": attr.label(
            mandatory = True,
            allow_single_file = True,
            doc = "The initramfs file (boot/initrd.img-<kver>), copied into " +
                  "image-<version>/boot/ alongside boot_files.",
        ),
        "platform_tar": attr.label(
            mandatory = True,
            allow_single_file = [".tar.gz", ".tar"],
            doc = "SONiC platform.tar.gz. Contents extracted into " +
                  "image-<version>/platform/.",
        ),
        "dockerfs": attr.label(
            allow_single_file = [".tar.gz", ".tar"],
            doc = "Optional dockerfs archive. If set, streamed (pigz -dc | " +
                  "tar_reprefix.py) re-rooted under image-<version>/docker/ into " +
                  "the mke2fs -d - stdin tar (the onie-image.conf DOCKERFS_DIR " +
                  "name the initrd union-mounts to /var/lib/docker). Not extracted.",
        ),
        "image_version": attr.string(
            mandatory = True,
            doc = "Image version string used to name the top-level " +
                  "image-<version>/ directory.",
        ),
        "machine": attr.string(
            mandatory = True,
            doc = "ONIE machine identifier (e.g. \"vs\"). Written to " +
                  "machine.conf as onie_machine.",
        ),
        "platform": attr.string(
            mandatory = True,
            doc = "ONIE platform identifier (e.g. \"x86_64-vs-r0\"). " +
                  "Written to machine.conf as onie_platform.",
        ),
        "onie_boot_staging": attr.label(
            mandatory = True,
            allow_single_file = [".tar"],
            doc = "Tar staging the ONIE-BOOT partition root (the onie_iso_extract " +
                  "output). Its onie/grub/grub.cfg is overwritten in place by the " +
                  "assembly action with a SONiC-first menu (default=0) + ONIE " +
                  "Rescue fallback -- no pack/unpack round-trip.",
        ),
        "disk_size_mb": attr.int(
            default = 32768,
            doc = "Total raw disk image size in MiB. Defaults to 32 GiB.",
        ),
        "onie_part_size_mb": attr.int(
            default = 128,
            doc = "ONIE-BOOT partition size in MiB. Matches the ONIE convention.",
        ),
        "bios_part_size_mb": attr.int(
            default = 1,
            doc = "BIOS Boot Partition size in MiB. 1 MiB is the standard size " +
                  "for embedding GRUB core.img.",
        ),
        "out": attr.string(
            default = "sonic.img.gz",
            doc = "Output filename (gzip-compressed raw image).",
        ),
        # Defaults use Label() relative to this .bzl's repo (@sonic_build_infra
        # internally; the apparent repo name differs between Bzlmod's owning
        # module and consumers, so a bare "//disk_image:..." label resolved at
        # rule-definition time is the portable form).
        "mke2fs": attr.label(
            default = Label("//disk_image:mke2fs"),
            executable = True,
            cfg = "exec",
        ),
        "sgdisk": attr.label(
            default = Label("//disk_image:sgdisk"),
            executable = True,
            cfg = "exec",
        ),
        "pigz": attr.label(
            default = Label("//disk_image:pigz"),
            executable = True,
            cfg = "exec",
        ),
        # GRUB host tools, now built from source (//grub:grub_mkimage,
        # //grub:grub_bios_setup). The attr is still a string (host path)
        # for the shell script; the Bazel-built binary path is resolved
        # from the tools attribute below. To revert to host tools, set
        # Source-built from GRUB 2.06 upstream.
        "grub_mkimage": attr.label(
            default = Label("//disk_image:grub_mkimage"),
            executable = True,
            cfg = "exec",
            doc = "grub-mkimage host tool (Bazel-built from source).",
        ),
        "grub_bios_setup": attr.label(
            default = Label("//disk_image:grub_bios_setup"),
            executable = True,
            cfg = "exec",
            doc = "grub-bios-setup host tool (Bazel-built from source).",
        ),
        "debugfs": attr.label(
            default = Label("//disk_image:debugfs"),
            executable = True,
            cfg = "exec",
            doc = "debugfs host tool (Bazel-built from e2fsprogs source). " +
                  "Injects char-dev(0,0) overlay2 whiteouts into the " +
                  "SONiC-OS ext4 with no host mknod.",
        ),
        "grub_platform_imgs": attr.label(
            default = Label("//grub:platform_imgs"),
            doc = "Filegroup of GRUB i386-pc platform images " +
                  "(boot.img, kernel.img, diskboot.img, lzma_decompress.img). " +
                  "Built from GRUB 2.06 source by //grub:build_platform_imgs. " +
                  "Copied into the grub-mkimage --directory " +
                  "alongside the ONIE ISO's *.mod files.",
        ),
        "grub_boot_img": attr.label(
            default = Label("//grub:boot.img"),
            allow_single_file = True,
            doc = "GRUB i386-pc boot.img (512B MBR stub). Built from " +
                  "source by //grub:build_platform_imgs genrule.",
        ),
        "grub_prefix": attr.string(
            default = "(hd0,gpt2)/onie/grub",
            doc = "GRUB prefix baked into core.img. Points at the ONIE-BOOT " +
                  "partition's /onie/grub directory -- where the assembly action " +
                  "writes the SONiC-first grub.cfg.",
        ),
        "_assemble_sh": attr.label(
            default = Label("//disk_image:sonic_disk_image_sh"),
            executable = True,
            cfg = "exec",
        ),
        "_tar_reprefix": attr.label(
            default = Label("//disk_image:tar_reprefix"),
            executable = True,
            cfg = "exec",
            doc = "py_binary streaming the dockerfs store re-rooted under " +
                  "image-<ver>/docker into the mke2fs -d - stdin tar.",
        ),
    },
    toolchains = [tar_lib.toolchain_type],
)
