#!/bin/bash
#
# Extract an ONIE-BOOT staging tar from an ONIE recovery ISO. Driven by
# sonic_rules/disk_image/onie_iso_extract.bzl; the output is consumed by
# T8 sonic_disk_image to populate the ONIE-BOOT ext4 partition.
#
# Usage:
#   onie_iso_extract.sh <bsdtar> <iso> <onie_boot_tar_out>

set -euo pipefail

if [ "$#" -lt 3 ]; then
    echo "usage: $0 <bsdtar> <iso> <onie_boot_tar_out> [grub_i386pc_tar]" >&2
    exit 2
fi

TAR="$1"
ISO="$2"
ONIE_OUT="$3"
# Optional: tar of a version-consistent i386-pc GRUB tree (modules + platform
# .img, at top level). Empty => keep the ISO's own (GRUB 2.02) modules.
GRUB_I386PC="${4:-}"

STAGE=$(mktemp -d)
trap 'rm -rf "$STAGE"' EXIT

# 1) Extract the ISO into a staging dir.
mkdir -p "$STAGE/iso"
"$TAR" -xf "$ISO" -C "$STAGE/iso"

# 2) Lay out an ONIE-BOOT partition tree under $STAGE/onie_boot/, then tar
#    it. The tar represents the root of the ONIE-BOOT ext4 partition (so
#    paths begin with "onie/", mirroring an actual ONIE install).
ONIE_ROOT="$STAGE/onie_boot"
mkdir -p "$ONIE_ROOT/onie/grub/i386-pc"

# Kernel + initrd from the ISO root.
cp "$STAGE/iso/vmlinuz" "$ONIE_ROOT/onie/vmlinuz"
cp "$STAGE/iso/initrd.xz" "$ONIE_ROOT/onie/initrd.xz"

# GRUB BIOS modules + .lst + platform images at /onie/grub/i386-pc/ (what
# `grub-install --target=i386-pc` lays down). The on-disk core.img is GRUB 2.06
# (hermetic grub-mkimage), but the ISO ships GRUB 2.02 modules -- loading a 2.02
# module into the 2.06 core panics at boot ("symbol `grub_disk_get_size' not
# found"). So when a version-consistent set is provided (GRUB_I386PC), use it;
# otherwise fall back to the ISO's own modules (kept for callers that do not
# boot, e.g. partition-structure tests). Use `cp -r .../.` so the source
# directory's own name is not duplicated under the target.
if [ -n "$GRUB_I386PC" ]; then
    mkdir -p "$STAGE/grub_i386pc"
    "$TAR" -xf "$GRUB_I386PC" -C "$STAGE/grub_i386pc"
    cp -r "$STAGE/grub_i386pc/." "$ONIE_ROOT/onie/grub/i386-pc/"
else
    cp -r "$STAGE/iso/boot/grub/i386-pc/." "$ONIE_ROOT/onie/grub/i386-pc/"
fi

# Minimal grub.cfg with a single "ONIE: Rescue" menuentry that boots the
# kernel + initrd staged above. The on-disk GRUB (loaded by core.img from
# the BIOS Boot Partition) finds this by searching for the partition
# labeled ONIE-BOOT and treating /onie/grub/grub.cfg as its config -- the
# standard ONIE convention. onie_boot_with_sonic_grub overwrites this
# file later to add the SONiC menuentry.
cat > "$ONIE_ROOT/onie/grub/grub.cfg" <<'EOF'
# Minimal ONIE-BOOT grub.cfg generated by sonic_rules/disk_image.
# Boots the ONIE rescue kernel staged at /onie/{vmlinuz,initrd.xz}.
serial --speed=115200 --word=8 --parity=no --stop=1
terminal_input console serial
terminal_output console serial
set timeout=3
set default=0

menuentry "ONIE: Rescue" --class gnu-linux --class onie {
    echo "ONIE: Rescue Mode ..."
    search --no-floppy --label --set=root ONIE-BOOT
    linux  /onie/vmlinuz console=tty0 console=ttyS0,115200n8 boot_reason=rescue
    initrd /onie/initrd.xz
}
EOF

# Pack the staging tree. ustar (bsdtar's default for `tar -c`) is the
# widely-supported format; mke2fs -d / libarchive both round-trip it.
"$TAR" -cf "$ONIE_OUT" -C "$ONIE_ROOT" onie
