"""Custom Bazel rule `kernel_debs_dist` — Tier 2 distribution target.

Implements the Tier 2 contract from
`specs/001-bazel-kernel-build/contracts/build-targets.md`:

    bazel run //:kernel_debs_dist \\
        --//bazel:arch=amd64 \\
        --//bazel:dest=/tmp/out

Behavior
--------
- When `--//bazel:dest=<path>` is non-empty, copies the deb set into
  `<path>/` (Makefile `$(addprefix $(DEST)/, ...)` equivalent).
- When empty (default), prints each deb's absolute `bazel-bin/...` path
  prefixed with `BAZEL_OUTPUTS:` to stdout — machine-parseable for
  callers that prefer to copy themselves.

Source-compile-only enforcement (FR-003 / FR-004)
-------------------------------------------------
The runtime script rejects `KERNEL_PROCURE_METHOD=download` with a
non-zero exit and an actionable message pointing at the Makefile. T035
enforces the same check at the wrapper-script layer; this rule guards
the env-var path that bypasses the wrapper.

Implementation notes
--------------------
The rule is `executable = True` so `bazel run` picks it up. The
generated shell script is pure POSIX bash — it does not invoke `make`.
It uses standard runfiles resolution
(`RUNFILES_DIR` / `RUNFILES_MANIFEST_FILE` / `${BASH_SOURCE[0]}.runfiles`
fallback) so it works under both `bazel run` and direct invocation of
the runfiles tree.
"""

load("@bazel_skylib//rules:common_settings.bzl", "BuildSettingInfo")

_SCRIPT_TEMPLATE = """#!/usr/bin/env bash
# Auto-generated by //bazel:kernel_debs_dist.bzl. Do not edit.
set -euo pipefail

if [ "${{KERNEL_PROCURE_METHOD:-}}" = "download" ]; then
    echo "kernel_debs_dist: KERNEL_PROCURE_METHOD=download is not supported by the Bazel build (out of scope per FR-003)." >&2
    echo "  Use the Makefile for download mode: 'make ... KERNEL_PROCURE_METHOD=download'" >&2
    exit 1
fi

# Standard bash runfiles resolution. See
# https://github.com/bazelbuild/bazel/blob/master/tools/bash/runfiles/runfiles.bash
_resolve_runfiles_dir() {{
    if [ -n "${{RUNFILES_DIR:-}}" ] && [ -d "${{RUNFILES_DIR}}" ]; then
        echo "${{RUNFILES_DIR}}"
        return
    fi
    if [ -n "${{RUNFILES_MANIFEST_FILE:-}}" ]; then
        # Manifest mode: derive directory by stripping `_manifest` suffix
        # if present, else use the file's parent.
        local mf="${{RUNFILES_MANIFEST_FILE}}"
        if [ -d "${{mf%_manifest}}" ]; then
            echo "${{mf%_manifest}}"
            return
        fi
    fi
    if [ -d "${{BASH_SOURCE[0]}}.runfiles" ]; then
        echo "${{BASH_SOURCE[0]}}.runfiles"
        return
    fi
    # Last-ditch: walk upward looking for *.runfiles
    local self
    self="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"
    while [ "${{self}}" != "/" ]; do
        if [ -d "${{self}}.runfiles" ]; then
            echo "${{self}}.runfiles"
            return
        fi
        self="$(dirname "${{self}}")"
    done
    echo "kernel_debs_dist: cannot locate runfiles directory" >&2
    exit 1
}}

_resolve_deb() {{
    local rel="$1"
    local rdir
    rdir="$(_resolve_runfiles_dir)"
    # Try workspace-qualified path first; fall back to the bare rel.
    local candidates=(
        "${{rdir}}/_main/${{rel}}"
        "${{rdir}}/${{rel}}"
    )
    for c in "${{candidates[@]}}"; do
        if [ -e "${{c}}" ]; then
            (cd "$(dirname "${{c}}")" && printf '%s/%s\\n' "$(pwd)" "$(basename "${{c}}")")
            return
        fi
    done
    echo "kernel_debs_dist: cannot locate deb in runfiles: ${{rel}}" >&2
    exit 1
}}

DEST={dest_value_quoted}
DEBS=(
{deb_lines}
)

if [ -n "${{DEST}}" ]; then
    mkdir -p "${{DEST}}"
    for rel in "${{DEBS[@]}}"; do
        src="$(_resolve_deb "${{rel}}")"
        cp -L "${{src}}" "${{DEST}}/$(basename "${{src}}")"
    done
else
    for rel in "${{DEBS[@]}}"; do
        src="$(_resolve_deb "${{rel}}")"
        printf 'BAZEL_OUTPUTS:%s\\n' "${{src}}"
    done
fi
"""

def _shell_quote(s):
    """Single-quote a string for safe inclusion in a bash script."""
    return "'" + s.replace("'", "'\\''") + "'"

def _kernel_debs_dist_impl(ctx):
    dest_value = ctx.attr.dest[BuildSettingInfo].value

    deb_files = ctx.files.debs
    if not deb_files:
        fail("kernel_debs_dist: `debs` resolved to no files")

    deb_lines = "\n".join([
        "    " + _shell_quote(f.short_path)
        for f in deb_files
    ])

    script = ctx.actions.declare_file(ctx.label.name + ".sh")
    ctx.actions.write(
        output = script,
        content = _SCRIPT_TEMPLATE.format(
            dest_value_quoted = _shell_quote(dest_value),
            deb_lines = deb_lines,
        ),
        is_executable = True,
    )

    runfiles = ctx.runfiles(files = deb_files)
    return [DefaultInfo(
        files = depset([script]),
        executable = script,
        runfiles = runfiles,
    )]

_kernel_debs_dist = rule(
    implementation = _kernel_debs_dist_impl,
    attrs = {
        "debs": attr.label(
            allow_files = True,
            mandatory = True,
            doc = "Label of a filegroup (or single file) producing the .deb set to distribute.",
        ),
        "dest": attr.label(
            default = "//kernel:dest",
            providers = [BuildSettingInfo],
            doc = "Label of the //kernel:dest string_flag.",
        ),
    },
    executable = True,
    doc = "Copy the kernel deb set into --//bazel:dest, or print bazel-bin paths.",
)

def kernel_debs_dist(name, debs, dest = "@sonic_build_infra//kernel:dest", **kwargs):
    """Copy a set of .deb files into $DEST/ (when set) or print their paths.

    Behavior:
      - If `--//bazel:dest=<path>` is set at run time and <path> is non-empty:
          on `bazel run //:kernel_debs_dist`, copy each .deb in `debs` into <path>/.
      - If <path> is empty (default):
          on `bazel run //:kernel_debs_dist`, print each .deb's bazel-bin path
          prefixed with "BAZEL_OUTPUTS:" so callers can parse and copy themselves.

    Equivalent to the existing Makefile's `$(addprefix $(DEST)/, ...)`.

    Args:
      name: target name.
      debs: label or label_list of .deb files (typically `:kernel_debs` filegroup).
      dest: label of the //bazel:dest string_flag (default).
      **kwargs: passed through to the underlying rule (e.g. `visibility`, `tags`).
    """
    _kernel_debs_dist(
        name = name,
        debs = debs,
        dest = dest,
        **kwargs
    )
