# Auto-generated by the debian_kernel_sources repo rule.
# Exposes the PURE patched Debian 6.1.123 kernel source tree (no config — config
# generation is a build action: see bazel/debian_kernel_config.bzl).

package(default_visibility = ["//visibility:public"])

# The whole patched source tree. `debian_kernel_config` and `kernel_build`
# consume this as their input root.
filegroup(
    name = "source_tree",
    srcs = glob(
        ["{BUILD_DIR}/**"],
        exclude = [
            "{BUILD_DIR}/**/.git/**",
        ],
        allow_empty = False,
    ),
)

# Bare `@kernel_sources` resolves to `@kernel_sources//:kernel_sources`.
filegroup(
    name = "kernel_sources",
    srcs = [":source_tree"],
)

filegroup(
    name = "all",
    srcs = [":source_tree"],
)
